-- Seed: heritage_sites (Official Mandaluyong list) — 31 sites
USE tcims_db;
TRUNCATE TABLE heritage_sites;
INSERT INTO heritage_sites (name, category, est, location, description, significance, status, coordinates, image) VALUES
('San Felipe Neri Church','Church','1863','Boni Avenue, Mandaluyong City','One of the oldest churches in the metropolis, established in 1863 as the core of the original pueblo of San Felipe Neri.','The birthplace of the city''s religious and cultural identity.','Well-maintained','14.5794, 121.0359',''),
('San Roque de Mandaluyong Church','Church','—','Pulog St., Brgy. Barangka Ilaya, Mandaluyong City','Parish church serving the Barangka Ilaya community.','A long-standing community parish.','Well-maintained','14.5794, 121.0359',''),
('Villa San Miguel - Archbishop''s Place','Abbey','—','Shaw Blvd. cor. E. Rodriguez St., Mandaluyong City','Official residence of the Archbishop of Manila.','Important ecclesiastical seat of the Archdiocese of Manila.','Well-maintained','14.5794, 121.0359',''),
('St. Francis of Assisi Church','Church','—','Shaw Blvd., Mandaluyong City','Parish church along Shaw Boulevard.','A prominent place of worship in the city.','Well-maintained','14.5794, 121.0359',''),
('Santuario de San Jose Parish Church','Church','—','Greenhills, Mandaluyong City','Parish church serving the Greenhills community.','Center of worship in the Greenhills area.','Well-maintained','14.5794, 121.0359',''),
('Our Lady of the Abandoned Parish','Church','—','Coronado St., Brgy. Hulo, Mandaluyong City','Riverside parish in Barangay Hulo.','A historic parish near the Pasig River.','Well-maintained','14.5794, 121.0359',''),
('Our Lady of Fatima Parish Church','Church','—','Liko Mariveles St., Brgy. Highway Hills, Mandaluyong City','Parish church serving Highway Hills.','Community church of the Highway Hills district.','Well-maintained','14.5794, 121.0359',''),
('Sacred Heart of Jesus Parish Church','Church','—','Mandaluyong City','Parish church devoted to the Sacred Heart of Jesus.','A center of devotion in the city.','Well-maintained','14.5794, 121.0359',''),
('Saint Dominic Savio Parish Church','Church','—','Mandaluyong City','Parish church named after St. Dominic Savio.','A community place of worship.','Well-maintained','14.5794, 121.0359',''),
('Archdiocese of the Divine Mercy','Church','—','Maysilo Circle, Mandaluyong City','Shrine devoted to the Divine Mercy at Maysilo Circle.','Focal point of religious devotion in the city center.','Well-maintained','14.5794, 121.0359',''),
('Tatlong Bayani Statue','Historical Landmark','—','Plaza Tatlong Bayani, Brgy. Hagdang Bato Itaas, Mandaluyong City','Statue honoring three local heroes of Mandaluyong.','Commemorates Mandaleño heroism.','Well-maintained','14.5794, 121.0359',''),
('Liberation Marker','Historical Landmark','—','Gen. Kalentong St., Brgy. Pag-Asa, Mandaluyong City','Marker commemorating the liberation of Mandaluyong.','Reminder of the city''s wartime history.','Well-maintained','14.5794, 121.0359',''),
('Dambana ng Ala-Ala','Historical Landmark','—','Maysilo Circle, Mandaluyong City','Memorial shrine of remembrance.','Honors the memory of fallen Mandaleños.','Well-maintained','14.5794, 121.0359',''),
('Dove of Peace','Historical Landmark','—','Mandaluyong City','Monument symbolizing peace.','A symbol of unity and peace for the city.','Well-maintained','14.5794, 121.0359',''),
('Bantayog ng Kabataan','Historical Landmark','—','Mandaluyong City Hall Complex','Monument dedicated to the youth.','Celebrates the role of the youth in the community.','Well-maintained','14.5794, 121.0359',''),
('National Center for Mental Health','Institution','—','9 de Pebrero St., Mandaluyong City','The country''s main psychiatric hospital.','A major national health institution based in the city.','Well-maintained','14.5794, 121.0359',''),
('Correctional Institution for Women','Institution','—','Welfareville Compound, Mandaluyong City','Historic penal institution for women.','A notable institutional landmark in Welfareville.','Well-maintained','14.5794, 121.0359',''),
('Asian Development Bank','Institution','—','ADB Ave., Ortigas Center, Mandaluyong City','Headquarters of the Asian Development Bank.','A globally significant institution located in the city.','Well-maintained','14.5794, 121.0359',''),
('Wack-Wack Golf and Country Club','Institution','—','Wack-Wack, Mandaluyong City','Internationally known private golf course.','A premier sports and recreation landmark.','Well-maintained','14.5794, 121.0359',''),
('San Miguel Main Office','Institution','—','Mandaluyong City','Corporate office of San Miguel.','A major corporate landmark in the city.','Well-maintained','14.5794, 121.0359',''),
('Don Bosco Technical College','School','—','Mandaluyong City','Catholic technical college.','A long-established educational institution.','Well-maintained','14.5794, 121.0359',''),
('Jose Rizal University','School','—','Shaw Blvd., Mandaluyong City','Private university along Shaw Boulevard.','One of the city''s notable universities.','Well-maintained','14.5794, 121.0359',''),
('Rizal Technological University','School','—','Boni Avenue, Mandaluyong City','State university offering technical programs.','A key public higher-education institution.','Well-maintained','14.5794, 121.0359',''),
('La Salle Greenhills','School','—','Ortigas Ave., Mandaluyong City','Private Catholic school for boys.','A prominent educational institution.','Well-maintained','14.5794, 121.0359',''),
('Lourdes School of Mandaluyong','School','—','Shaw Blvd., Mandaluyong City','Private Catholic school.','A well-known school in the city.','Well-maintained','14.5794, 121.0359',''),
('Arellano University - Plaridel','School','—','Mandaluyong City','Campus of Arellano University.','A notable educational institution.','Well-maintained','14.5794, 121.0359',''),
('Mandaluyong Elementary School','School','—','Mandaluyong City','Public elementary school.','One of the city''s foundational public schools.','Well-maintained','14.5794, 121.0359',''),
('Hardin ng Pag-Asa','Park','—','Mandaluyong City','Public garden park.','A green public space for residents.','Well-maintained','14.5794, 121.0359',''),
('Vergara Linear Park','Park','—','Brgy. Vergara, Mandaluyong City','Linear park in Barangay Vergara.','A community recreational space.','Well-maintained','14.5794, 121.0359',''),
('Garden of Life Park','Park','—','Brgy. Vergara, Mandaluyong City','Public park promoting greenery.','An environmental and recreational landmark.','Well-maintained','14.5794, 121.0359','');
