-- Seed: events (Calendar of Activities 2026) — 47 events
USE tcims_db;
TRUNCATE TABLE events;
INSERT INTO events (name, month, category, venue, participants, status, image) VALUES
('Regular Monday Morning Programs','January','Morning Programs','Mandaluyong City',0,'Upcoming',''),
('Sto. Niño Images Exhibit','January','Cultural & Religious Exhibit','Mandaluyong City',0,'Upcoming',''),
('Mandaluyong Liberation & Cityhood Anniversary','February','Historical Event','Mandaluyong City',0,'Upcoming',''),
('Miss Mandaluyong Pageant','February','Beauty Pageant','Mandaluyong City',0,'Upcoming',''),
('Bilbiling Mandaluyong Pageant','February','Beauty Pageant','Mandaluyong City',0,'Upcoming',''),
('Kasalang Bayan','February','Community Program','Mandaluyong City',0,'Upcoming',''),
('Mandaluyong Hymn Making Contest','February','Music Competition','Mandaluyong City',0,'Upcoming',''),
('Trade Fair Exhibits','February','Trade Fair','Mandaluyong City',0,'Upcoming',''),
('National Arts Month','February','Cultural & Arts Program','Mandaluyong City',0,'Upcoming',''),
('Lenten Season Presentation','March/April','Religious Festival','Mandaluyong City',0,'Upcoming',''),
('Pabasa ng Bayan / Cenakulo / Visita Iglesia','March/April','Religious Festival','Mandaluyong City',0,'Upcoming',''),
('Carozza-Lenten Images Exhibit','March/April','Cultural & Religious Exhibit','Mandaluyong City',0,'Upcoming',''),
('Araw ng Kagitingan','March/April','Historical Event','Mandaluyong City',0,'Upcoming',''),
('Cultural & Arts Workshop','March/April','Cultural & Arts Program','Mandaluyong City',0,'Upcoming',''),
('National Women''s Month (March)','March/April','National Observance','Mandaluyong City',0,'Upcoming',''),
('National Literature Month (April)','March/April','Cultural & Arts Program','Mandaluyong City',0,'Upcoming',''),
('Flavors of NCR (Food Festival - ATO-NCR)','March/April','Food Trade Fair','Mandaluyong City',0,'Upcoming',''),
('Maytime Festivals','May','Religious/Fashion Events','Mandaluyong City',0,'Upcoming',''),
('Santa Cruzan / Flores de Mayo','May','Religious/Fashion Events','Mandaluyong City',0,'Upcoming',''),
('National Heritage Month','May','Cultural & Arts Program','Mandaluyong City',0,'Upcoming',''),
('Araw ng Kalayaan','June','National Observance','Mandaluyong City',0,'Upcoming',''),
('Dr. Jose Rizal''s Birth Anniversary','June','National Observance','Mandaluyong City',0,'Upcoming',''),
('Filipino-Chinese Friendship Day','June','National Observance','Mandaluyong City',0,'Upcoming',''),
('Saints Images Exhibit','July','Cultural & Religious Exhibit','Mandaluyong City',0,'Upcoming',''),
('National Nutrition Month','July','National Observance','Mandaluyong City',0,'Upcoming',''),
('National Culture Consciousness Week','July','National Observance','Mandaluyong City',0,'Upcoming',''),
('Linggo ng Musikang Pilipino','July','National Observance','Mandaluyong City',0,'Upcoming',''),
('Iglesia ni Cristo Day','July','National Observance','Mandaluyong City',0,'Upcoming',''),
('29 de Agosto - Araw ng mga Bayani','August','Historical Event','Mandaluyong City',0,'Upcoming',''),
('Buwan ng Wikang Pambansa','August','National Observance','Mandaluyong City',0,'Upcoming',''),
('National History Month','August','National Observance','Mandaluyong City',0,'Upcoming',''),
('Our Lady of Peñafrancia Feast','September','Religious Event','Mandaluyong City',0,'Upcoming',''),
('National Tourism Week','September','National Observance','Mandaluyong City',0,'Upcoming',''),
('National Literacy Day','September','Cultural & Arts Program','Mandaluyong City',0,'Upcoming',''),
('Annual Convention of Association of Tourism Officers','October','Conference','Mandaluyong City',0,'Upcoming',''),
('Marian Images Exhibit','October','Cultural & Religious Exhibit','Mandaluyong City',0,'Upcoming',''),
('Museums and Galleries Month','October','National Observance','Mandaluyong City',0,'Upcoming',''),
('National Archives Day','October','National Observance','Mandaluyong City',0,'Upcoming',''),
('All Soul''s Day','November','Religious Event','Mandaluyong City',0,'Upcoming',''),
('Lavandero Festival','November','City Festival','Mandaluyong City',0,'Upcoming',''),
('Pistang Daluyong','November','Cultural Event','Mandaluyong City',0,'Upcoming',''),
('Library and Information Services Month','November','National Observance','Mandaluyong City',0,'Upcoming',''),
('Bonifacio Day','November','National Observance','Mandaluyong City',0,'Upcoming',''),
('Paskuhan sa Lungsod','December','Christmas Festival / Trade Fair','Mandaluyong City',0,'Upcoming',''),
('Daluyong sa Mandaluyong','December','Christmas Festival / Trade Fair','Mandaluyong City',0,'Upcoming',''),
('Christmas Parol Contest','December','Christmas Festival / Trade Fair','Mandaluyong City',0,'Upcoming',''),
('Rizal Day','December','National Observance','Mandaluyong City',0,'Upcoming','');
